### ISSUE TITLE
Unsupported argument 'openid_token_file'

### ISSUE THREAD

**Issue by ross-paypay** [tconbeer/harlequin-mysql#31]
Hello, trying to use harlequin to connect to a local database running in Docker for testing.

Docker compose file
```yaml
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
```

I am able to connect with the mysql cli like 
```sh
mysql -u root -ppass -h 127.0.0.1 mysql
```

However, when I connect with Harlequin I am getting an error 
```sh
harlequin -a mysql -h 127.0.0.1 -u root --password pass --database mysql --ssl-disabled
╭─ Harlequin could not connect to your database. ──────────────────────────────╮
│ Connection configuration not valid: Unsupported argument 'openid_token_file' │
╰──────────────────────────────────────────────────────────────────────────────╯
```

## Version info 

I am on MacOS and install harlequin via Homebrew and the mysql plugin using uv

```
> harlequin --version
harlequin, version 2.1.1

Installed Adapters:
  - odbc, version 0.3.1
  - mysql, version 1.1.0
  - postgres, version 1.2.0
  - duckdb, version 2.1.1
  - sqlite, version 2.1.1

> mysql --version
mysql  Ver 8.4.4 for macos15.2 on arm64 (Homebrew)
```
